version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    ports:
      - 4999:5432

  main:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
    - .:/go/src/app

#    build:
#      context: .
#      dockerfile: dockerfile-db
